name: Build and test installer
on:
  push:
    branches:
      - debug

jobs:
  build-installer:
    name: Build installer
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        target_arch: ["osx-64"]
    steps:
      - uses: actions/checkout@v2
      - id: get-date
        run: echo "::set-output name=year-and-week::$(date +"%Y-W%U")"
        shell: bash
      - name: Keep constructor cache between invocations
        # This is big help to avoid needing to transmuting packages every time
        id: cache-transmuted-packages
        uses: actions/cache@v2
        with:
          path: ~/.conda/constructor
          key: ${{ runner.os }}-${{ matrix.target_arch }}-constructor-${{ steps.get-date.outputs.year-and-week }}
      - name: Prepare environment
        uses: conda-incubator/setup-miniconda@master
        with:
          environment-file: scripts/environment.yml
          miniforge-variant: Mambaforge
          use-mamba: true
      - name: Create installer
        run: |
          CONDA_SUBDIR=${{ matrix.target_arch }} mamba create --name constructor-${{ matrix.target_arch }} 'micromamba>=0.22'
          CONDA_STANDALONE_PATH="$(conda info --envs | grep constructor-${{ matrix.target_arch }} | sed -E 's@([^ ]+ +)@@g')/bin/micromamba"
          pip install git+http://github.com/conda/constructor.git@3.3.1
          if [ "${{ matrix.target_arch }}" = osx-64 ]; then
              export CONDA_OVERRIDE_OSX=10.12
          elif [ "${{ matrix.target_arch }}" = linux-64 ]; then
              export CONDA_OVERRIDE_GLIBC=2.17
          fi
          CONDA_SUBDIR=${{ matrix.target_arch }} constructor . --platform="${{ matrix.target_arch }}" --conda-exe="${CONDA_STANDALONE_PATH}"
      - name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          name: installer-${{ matrix.target_arch }}
          path: DIRACOS-*.sh

  macos-tests:
    name: macOS tests
    if: github.repository == 'DIRACGrid/DIRACOS2'
    needs: build-installer
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12]
    steps:
      - uses: actions/checkout@v2
      - name: Download installer
        uses: actions/download-artifact@v2
        with:
          name: installer-osx-64
      - name: Run tests
        run: |
           bash DIRACOS-*.sh
           set -x
           pwd
           ls -l diracos/bin
           ls -R diracos/
           cd $PWD
           source diracos/diracosrc
           pip install DIRAC
